// This file is used by eslint_app.bat

// Placeholders for global modules
function $() {}
const THREE = {};
const Metro = {};
const TweenMax = {};
const Linear = {};
const QRCode = {};
const io = {};
const _ = {};
const YAML = {};
const ace = {};
const IconPicker = {};

// Dummy reference to functions that are used by html
// eslint-disable-next-line no-unused-vars
const usedFunctions = {
	gotoHistory,
	getWebGL2ErrorMessage,
	cancelUpdateTimer,
	saveDiagnostics,
	toggleAutoStart,
	toggleAggressiveHomeReset,
	onMacroShortcutInputClick,
	onMacroShortcutInputChange,
	createMacro,
	createMacroFromFile,
	runJsMacro,
	macroContextMenu,
	moveMacro,
	confirmMacroDelete,
	backupMacro,
	backupMacroAll,
	importMacroBackupFile,
	importMacroAll,
	selectedMacroGroup,
	renameMacroGroup,
	selectMacroTab,
	macroTabContextMenu,
	moveMacroToGroup,
	changeViewSettings,
	loadJobFile,
	reloadJobFile,
	previewGcode,
	saveGcode,
	clearGcode,
	invokeOpenDialog,
	toTitleCase,
	selectMachine,
	loadGrblBackupFile,
	restoreAutoBackup,
	backupGrblSettings,
	grblSaveSettings,
	showBasicSettings,
	showAdvSettings,
	revertGrblSetting,
	clearSettings,
	clearWCO,
	clearEEPROM,
	onSettingsTableDraw,
	onSettingsTableCreate,
	lastsysinfo,
	scanNetwork,
	selectPort,
	closePort,
	spindleDelay,
	pauseSpindle,
	manualcontrolPanel,
	grblPanel,
	fluidncPanel,
	updatePanel,
	troubleshootingPanel,
	setADist,
	toggleWCS,
	onDroClick,
	onDroKeydown,
	onDroBlur,
	jog,
	jogXY,
	jogWidget,
	onShortcutInputClick,
	onShortcutInputChange,
	keyboardShortcutsEditor,
	simSpeed,
	runSimFrom,
	simStepBack,
	simSetProgress,
	simDragStart,
	simDragStop,
	simStepForward,
	xstepspermm,
	ystepspermm,
	zstepspermm,
	actuatorselect,
	applycalibrationx,
	xstepscalibrate,
	xcalslide1,
	xcalslide2,
	xcalslide3,
	applycalibrationy,
	ystepscalibrate,
	ycalslide1,
	ycalslide2,
	ycalslide3,
	applycalibrationz,
	zstepscalibrate,
	zcalslide1,
	zcalslide2,
	zcalslide3,
	penUpSend,
	penDownSend,
	servocalslide1,
	servocalslide2,
	servocalslide3,
	closeServoCal,
	openProbeDialog,
	openProbeXDialog,
	openProbeYDialog,
	openProbeZDialog,
	probeendmilltab,
	confirmProbeInPlace,
	runProbeNew,
	editCustomProbe,
	saveEditCustomProbe,
	populateSurfaceToolForm,
	heightmapAutoSize,
	editHeightmapSettings,
	generateHeightmap,
	loadHeightmap,
	saveHeightmap,
	revertHeightmap,
	applyHeightmap,
	updateHeightmapMenu,
	toggleHeightmapTools,
	flashToolBoard,
	openFlashingTool,
	readEspFirmwareFile,
	populateFlashDrivePrepForm,
	interfaceReadyToCopy,
	showJobLog,
	recoverCrashedJob,
	replaceConeWith,
	populateToolChanges,
	runGcodeAllTools,
	runGcodeSection,
};
